name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main  # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # <-- Important!

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
