name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read       # for actions/checkout
  actions: read
  security-events: write
  id-token: write      # sometimes needed for external integrations
  packages: read       # if using Docker packages
  artifacts: write     # required for actions/upload-artifact

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Local Server
        run: |
          nohup python3 -m http.server 8080 &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Create empty report files
        run: |
          touch report_json.json report_md.md report_html.html
          chmod a+w report_json.json report_md.md report_html.html

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
