name: OWASP ZAP Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create zapnet

      - name: Build Test App
        run: |
          docker build -t zap-test-app .
          docker run -d --name test-app --network zapnet -p 8080:80 zap-test-app

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://test-app:80'  # Use container name
