name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main  # make sure this matches your default branch name
  workflow_dispatch:

# ✅ Add correct permissions to allow issue creation
permissions:
  contents: read
  issues: write  # <-- THIS FIXES THE ERROR

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'  # or your app URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
