name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  issues: write      # allows ZAP to open an Issue when warnings exist
  actions: read
  artifacts: write   # needed for upload-artifact@v4

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4          # (v4 is current)

      # ──────────────────────────────────────────────────────────
      # Start or build your target application here.
      # Example: simple static server on port 8080
      - name: Start target app (example)
        run: |
          nohup python3 -m http.server 8080 &
          sleep 15                       # give it time to boot
      # ──────────────────────────────────────────────────────────

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'

      # ─────── Upload scan reports (needs v4 now) ───────
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload Markdown report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md

      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
