name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

# ✅ Add permissions to create GitHub Issues
permissions:
  contents: read
  issues: write  # This line is critical to fix the error

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
