name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker network
        run: docker network create zap-net

      - name: Start vulnerable app (Juice Shop)
        run: |
          docker run -d --rm \
            --network zap-net \
            --name vulnerableweb \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 30

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: http://vulnerableweb:3000
        env:
          DOCKER_NETWORK: zap-net
        continue-on-error: true

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html

