name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start target application (replace with your real app command)
        run: |
          docker run -d -p 8080:80 --name webapp nginx
        # 📝 Replace `nginx` with your actual app/container

      - name: Wait for target to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 10

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
