name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Permissions
      run: sudo chmod -R 777 ${{ github.workspace }}

    - name: Start Target App (Example)
      run: |
        nohup python3 -m http.server 8080 &
        sleep 15

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8080'
        cmd_options: '-J report_json.json -w report_md.md -r report_html.html'

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP-HTML-Report
        path: report_html.html

    - name: Upload Markdown Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP-MD-Report
        path: report_md.md

    - name: Upload JSON Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP-JSON-Report
        path: report_json.json
