name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker network
        run: docker network create zap-net

      - name: Run vulnerable web app container
        run: |
          docker run -d --rm \
            --name vulnerableweb \
            --network zap-net \
            bkimminich/juice-shop

      - name: Wait for vulnerable app to start
        run: sleep 30

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            --network zap-net \
            -v ${{ github.workspace }}:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://vulnerableweb:3000 \
              -r zap_report.html \
              -l INFO \
              -d
        continue-on-error: true

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      - name: Cleanup Docker
        if: always()
        run: |
          docker stop vulnerableweb || true
          docker network rm zap-net || true
